# Generated by Django 6.0.3 on 2026-04-05 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_restructure_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_nome', models.CharField(default='Ricardo Silva', max_length=120)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10)),
                ('fundo_troco_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sessão de caixa',
                'verbose_name_plural': 'Sessões de caixa',
                'ordering': ['-aberto_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'aberto')), fields=('status',), name='unique_open_cash_session')],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('abertura', 'Abertura'), ('sangria', 'Sangria'), ('suprimento', 'Suprimento'), ('fechamento', 'Fechamento')], max_length=12)),
                ('descricao', models.CharField(blank=True, max_length=160)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao_caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='inventory.sessaocaixa')),
            ],
            options={
                'verbose_name': 'Movimentação de caixa',
                'verbose_name_plural': 'Movimentações de caixa',
                'ordering': ['-criado_em', '-id'],
                'constraints': [models.UniqueConstraint(fields=('sessao_caixa', 'codigo'), name='unique_cash_movement_code_per_session')],
            },
        ),
    ]
