# Generated by Django 6.0.3 on 2026-04-05 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_sessaocaixa_movimentacaocaixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=24, unique=True)),
                ('status', models.CharField(choices=[('finalizada', 'Finalizada')], default='finalizada', max_length=12)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartao')], max_length=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('troco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=180)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('sessao_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='inventory.sessaocaixa')),
            ],
            options={
                'verbose_name': 'Venda no caixa',
                'verbose_name_plural': 'Vendas no caixa',
                'ordering': ['-criada_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemVendaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda_caixa', to='inventory.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventory.vendacaixa')),
            ],
            options={
                'verbose_name': 'Item de venda no caixa',
                'verbose_name_plural': 'Itens de venda no caixa',
                'ordering': ['id'],
            },
        ),
    ]
