# Generated by Django 6.0.3 on 2026-04-05 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sessaocaixa_diferenca_cartao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendacaixa',
            name='comanda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venda_caixa', to='inventory.comanda'),
        ),
    ]
