# Generated by Django 6.0.3 on 2026-04-06 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_vendacaixa_comanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='controla_estoque',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('g', 'Grama'), ('kg', 'Quilograma'), ('ml', 'Mililitro'), ('l', 'Litro'), ('porcao', 'Porcao')], default='un', max_length=10),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('uso_interno', 'Uso interno'), ('ajuste', 'Ajuste'), ('perda', 'Perda'), ('venda', 'Venda')], max_length=16)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_estoque', to='inventory.produto')),
            ],
            options={
                'verbose_name': 'Movimentacao de estoque',
                'verbose_name_plural': 'Movimentacoes de estoque',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
